# Testing OpenNRE

* Followed the instructions on this github to install it

In [55]:
import opennre
import os
import torch
import json

In [11]:
model = opennre.get_model('wiki80_bert_softmax')

I0109 18:13:51.323661 140734763410880 bert_encoder.py:19] Loading BERT pre-trained checkpoint.
I0109 18:13:51.325680 140734763410880 configuration_utils.py:182] loading configuration file /Users/GuruSenthil/.opennre/pretrain/bert-base-uncased/config.json
I0109 18:13:51.326586 140734763410880 configuration_utils.py:199] Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab

In [12]:
model.infer({'text': 'He was the son of Máel Dúin mac Máele Fithrich, and grandson of the high king Áed Uaridnach (died 612).', 'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})

('father', 0.9925805330276489)

In [19]:
sentence_encoder = opennre.encoder.BERTEncoder(
            max_length=80, pretrain_path=os.path.join('/Users/GuruSenthil/.opennre', 'pretrain/bert-base-uncased'))

I0109 19:55:25.713931 140734763410880 bert_encoder.py:19] Loading BERT pre-trained checkpoint.
I0109 19:55:25.715536 140734763410880 configuration_utils.py:182] loading configuration file /Users/GuruSenthil/.opennre/pretrain/bert-base-uncased/config.json
I0109 19:55:25.716428 140734763410880 configuration_utils.py:199] Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab

In [40]:
items = sentence_encoder.tokenize({'text': 'austin is the capital of texas', 'h': {'pos': (0, 6)}, 't': {'pos': (25, 30)}})
a = sentence_encoder(*items)

In [41]:
items = sentence_encoder.tokenize({'text': 'meow is the capital of cat', 'h': {'pos': (0, 4)}, 't': {'pos': (23, 26)}})
b = sentence_encoder(*items)


In [51]:
items = sentence_encoder.tokenize({'text': "meow is donald trump's friend. and meow is a cat.", 'h': {'pos': (0, 4)}, 't': {'pos': (8, 20)}})
c = sentence_encoder(*items)

In [52]:
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
cos(a,b)

tensor([0.9665], grad_fn=<DivBackward0>)

In [53]:
cos(b,c)

tensor([0.8142], grad_fn=<DivBackward0>)

In [58]:
root_path = "/Users/GuruSenthil/.opennre"
ckpt = '/Users/GuruSenthil/.opennre/pretrain/nre/wiki80_bert_softmax.pth.tar'
rel2id = json.load(open(os.path.join(root_path, 'benchmark/wiki80/wiki80_rel2id.json')))
sentence_encoder = opennre.encoder.BERTEncoder(
    max_length=80, pretrain_path=os.path.join(root_path, 'pretrain/bert-base-uncased'))
m = opennre.model.SoftmaxNN(sentence_encoder, len(rel2id), rel2id)
m.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])

I0109 21:21:30.306677 140734763410880 bert_encoder.py:19] Loading BERT pre-trained checkpoint.
I0109 21:21:30.309437 140734763410880 configuration_utils.py:182] loading configuration file /Users/GuruSenthil/.opennre/pretrain/bert-base-uncased/config.json
I0109 21:21:30.310675 140734763410880 configuration_utils.py:199] Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab

<All keys matched successfully>

In [65]:
items = sentence_encoder.tokenize({'text': "meow is donald trump's friend. and meow is a cat.", 'h': {'pos': (0, 4)}, 't': {'pos': (8, 20)}})
a = m(*items)
a

tensor([[-1.3427, -0.1440, -1.3654, -0.4375, -1.7786, -0.5298,  1.9023, -0.6984,
         -2.8205, -0.3486,  0.0706,  0.5511,  0.9234,  0.5459, -2.2748, -2.1622,
         -2.1507,  0.2960, -0.4731,  2.4915,  1.0260,  0.8903, -0.8175, -0.7492,
         -0.9382, -2.5027,  0.2545,  1.1382, -0.9117,  1.7248, -0.2244, -0.8402,
         -0.0466,  2.2004, -0.9679,  0.8496,  1.3005,  1.5516, -0.2336, -0.1541,
          1.9099,  1.9824,  4.8553,  0.9758, -4.1883, -1.1187,  5.0358, -2.7919,
         -0.7149, -0.1335,  2.2405, -2.0716,  0.4516, -2.3358, -0.0340,  1.0407,
          1.4622,  0.6326,  0.5264, -0.4178, -0.3764,  0.3265, -1.1930, -0.1548,
          0.9341, -0.4265, -0.6686,  0.9628,  0.0769, -0.2006, -0.8531, -2.1909,
         -0.6461, -1.2162,  2.6883, -0.4939,  1.0412,  1.7167, -0.8559, -0.6045]],
       grad_fn=<AddmmBackward>)

In [61]:
items = sentence_encoder.tokenize({'text': 'meow is the capital of cat', 'h': {'pos': (0, 4)}, 't': {'pos': (23, 26)}})
b = m(*items)
b

tensor([[ 2.1560, -0.1905, -0.6039, -2.9801, -1.7388,  0.5615,  0.5146, -0.7127,
         -0.6256, -1.5320, -1.1279,  0.6374, -0.9176,  6.5828, -0.5549,  0.1322,
          2.1347,  1.8245, -2.4338, -0.7260,  1.2941,  0.3351, -0.3702, -2.7036,
         -0.1676, -2.3188, -1.0749, -1.0955, -2.6997, -1.3087, -0.5501,  1.5541,
          9.0482, -0.5609, -0.4973, -0.0460, -0.0277,  3.0687,  2.3323,  1.0484,
         -1.4314, -0.2442, -0.7876,  1.0941, -1.8151, -1.5772,  3.0612, -0.5493,
         -2.5068, -1.8567, -0.2186, -0.8552,  1.5331, -0.2951,  0.0881, -1.4775,
         -1.1968, -1.5754,  3.9728, -0.8819,  0.2813, -0.3515, -2.7493,  3.3888,
          0.5984, -1.0252, -0.7704, -0.8025,  0.1246, -0.3000,  0.3585, -0.7857,
         -1.4500, -0.9740, -1.5255, -0.2581,  0.2017,  0.3956,  0.2308, -1.5301]],
       grad_fn=<AddmmBackward>)

In [62]:
items = sentence_encoder.tokenize({'text': 'austin is the capital of texas', 'h': {'pos': (0, 6)}, 't': {'pos': (25, 30)}})
c = m(*items)
c

tensor([[ 2.0487e+00,  5.0125e-01, -1.2646e+00, -2.7185e+00,  3.2718e+00,
         -9.7491e-01, -3.3797e+00,  2.8477e+00,  4.7379e-01, -3.3002e-01,
         -1.4340e+00, -2.7140e+00,  2.9508e-03, -9.0510e-01,  2.1070e+00,
         -3.1967e-01, -1.0099e+00, -1.4511e+00, -3.8937e-04, -1.7084e+00,
         -7.5802e-01, -2.9236e-01,  1.5564e-01, -2.4067e-01, -2.5359e+00,
         -1.4531e+00,  2.1920e-01, -3.6974e-01,  1.4170e+00, -1.1669e+00,
         -1.5002e+00,  2.0625e-01,  2.6768e+00, -1.7314e+00, -3.9138e+00,
          2.5759e+00, -1.3503e+00,  1.9748e+00,  2.3183e-01, -2.1805e+00,
         -2.9977e+00,  5.3179e-01,  4.7085e-01,  7.9911e-01, -1.5058e+00,
         -1.0703e+00,  2.7962e+00,  1.1350e+00,  7.6377e-01, -2.2252e+00,
         -1.6672e+00, -5.4009e-02,  1.1117e+00, -1.9170e+00,  9.6382e-01,
         -1.0127e+00, -5.8511e-02, -1.5312e+00,  3.7789e+00, -1.7765e+00,
         -1.0639e-01,  9.6908e-01, -5.1674e-01,  1.1604e+01,  6.5263e-01,
          4.5381e-01, -2.3814e+00,  2.

In [66]:
cos(b,a)

tensor([0.1791], grad_fn=<DivBackward0>)

In [67]:
cos(b,c)

tensor([0.3375], grad_fn=<DivBackward0>)